# Generated by Django 5.1.7 on 2025-08-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0004_alter_results_league_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='api_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('upcoming', 'upcoming'), ('in play', 'in play'), ('finished', 'finished'), ('canceled', 'canceled')], default='upcoming', max_length=20),
        ),
    ]
