# Generated by Django 5.1.7 on 2025-08-13 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0005_matches_api_id_alter_matches_match_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='matchodds',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='leagues',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matches',
            name='api_id',
        ),
        migrations.AddField(
            model_name='leagues',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matches',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leagues',
            name='sport',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='matches',
            name='commence_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='league',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='league_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MoxBet.leagues'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='sport',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='matchodds',
            unique_together={('match', 'market_type')},
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('payload', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoxBet.matches')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('extras', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MoxBet.team')),
            ],
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('details', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MoxBet.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MoxBet.team')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_transfers', to='MoxBet.team')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MoxBet.player')),
                ('to_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_transfers', to='MoxBet.team')),
            ],
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('lineup', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoxBet.matches')),
            ],
            options={
                'unique_together': {('match', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='FOOTBALL', max_length=64)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('standings', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MoxBet.leagues')),
            ],
            options={
                'unique_together': {('league', 'season', 'sport')},
            },
        ),
    ]
