# Generated by Django 5.1.7 on 2025-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0006_competition_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchodds',
            name='match',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
