# Generated by Django 5.1.7 on 2025-08-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0007_alter_matchodds_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchodds',
            name='odds',
            field=models.CharField(max_length=100),
        ),
    ]
