# Generated by Django 5.1.7 on 2025-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0008_alter_matchodds_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchodds',
            name='odds',
            field=models.JSONField(),
        ),
    ]
