# Generated by Django 5.1.7 on 2025-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0009_alter_matchodds_odds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='league_id',
        ),
        migrations.AlterField(
            model_name='matches',
            name='league',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
