# Generated by Django 5.1.7 on 2025-08-18 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0010_remove_matches_league_id_alter_matches_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='league_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MoxBet.leagues'),
        ),
    ]
