# Generated by Django 5.1.7 on 2025-08-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0011_matches_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchodds',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchodds', to='MoxBet.matches'),
        ),
    ]
