# Generated by Django 5.1.7 on 2025-08-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0012_alter_matchodds_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchodds',
            name='extras',
            field=models.JSONField(null=True),
        ),
    ]
