# Generated by Django 5.1.7 on 2025-08-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoxBet', '0013_matchodds_extras'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leagues',
            unique_together={('league', 'country', 'sport')},
        ),
    ]
